<?php

/**
 * @file
 * Activity Heatmap module.
 */

/**
 * Implements hook_menu().
 */
function activity_calendar_menu() {
  $items['admin/config/people/activity_calendar'] = [
   'title' => 'Activity calendar',
   'description' => 'Configure settings for activity calendar.',
   'type' => MENU_NORMAL_ITEM,
   'page callback' => 'backdrop_get_form',
   'page arguments' => ['activity_calendar_admin_form'],
   'access arguments' => ['administer site configuration'],
   'file' => 'activity_calendar.admin.inc',
];
return $items;
}

/**
 * Implements hook_user_view_alter().
 */
function activity_calendar_user_view_alter(&$build) {
  $config = config('activity_calendar.settings');
  $uid = $build['#account']->uid;
  // Load libraries.
  $path = backdrop_get_path('module', 'activity_calendar');
  backdrop_add_css($path . '/activity_calendar.css');
  backdrop_add_css($path . '/lib/cal-heatmap.css');
  backdrop_add_js($path . '/lib/d3.min.js');
  backdrop_add_js($path . '/lib/cal-heatmap.min.js');
  // Define calendar type and range parameter.
  if ($config->get('calendar_type') == 'monthly') {
    $calendar_type = 'month';
    $range = '12';
  }
  else {
    $calendar_type = 'year';
    $range = '1';
  }

  // Sync calendar with the system's first day of the week.
  if (config_get('system.date', 'first_day') == '1') {
    $first_day = "true";
  }
  else {
    $first_day = "false";
  }

  // Collect node points.
  if ($config->get('nodes') == 1) {
    $prefix = 'node_type_';
    foreach ($config->get() as $option => $value) {
      if (strpos($option, $prefix) !== FALSE) {
        if ($value == TRUE) {
          $content_type = str_replace($prefix, "", $option);
          $nodes = db_select('node', 'n')
          ->fields('n', array('nid', 'created'))
          ->condition('n.uid', $uid)
          ->condition('n.type', $content_type)
          ->condition('n.status', '1')
          ->execute()->fetchAll();
          foreach ($nodes as $node) {
            $user_activity[$node->created] = intval($config->get('node_points'));
          }
        }
      }
    }
  }

  // Collect comment points.
  if ($config->get('comments') == 1) {
    $comments = db_select('comment', 'c')
    ->fields('c', array('cid', 'created'))
    ->condition('c.uid', $uid)
    ->condition('c.status', '1')
    ->execute()->fetchAll();
    foreach ($comments as $comment) {
      $user_activity[$comment->created] = intval($config->get('comment_points'));
    }
  }

  // Calling all modules implementing 'hook_activity_calendar':
  module_invoke_all('calendar');
  foreach (module_implements('calendar') as $module) {
    $result[$module] = module_invoke($module, 'calendar');
    $user_activity = $user_activity + $result['flag_activity']['user_activity'];
  }

  // Display the control button only if user has nodes for previous years.
  $first_node_date = min(array_keys($user_activity));
  $start = date("Y", $first_node_date);
  $control_buttons = '';
  if ($start < date("Y", time())) {
    $control_buttons = '<div class="control-buttons">
    <button id="PreviousDomain" class="button previous">' . t('Previous') . '</button>
    <button id="CurrentDomain" class="button current">' . t('Current') . '</button>
    <button id="NextDomain" class="button next">' . t('Next') . '</button>
    </div>';
  }

  // Build activity heatmap calendar.
  $build['heatmap'] = [
    '#type' => 'item',
    '#title' => t('Activity calendar'),
    '#weight' => '100',
    '#markup' => '
    <div id="activity-calendar">
    ' . $control_buttons . '
    <div id="heatmap"></div>
    </div>
    <script type="text/javascript">
    var user_activity = ' . json_encode($user_activity) . ';
    var cal = new CalHeatMap();
    cal.init({
      itemNamespace: "backdropcms.org",
      legendColors: ["' . $config->get('color_min') . '","' . $config->get('color_max') . '"],
    	itemSelector: "#heatmap",
    	domain: "' . $calendar_type . '",
    	subDomain: "day",
    	data: user_activity,
      minDate: new Date(' . $start . ', 1),
      start: new Date(' . date("Y") . ', 0),
      maxDate: new Date(' . date("Y") . ', 0),
      onMinDomainReached: function(hit) {
      if (hit) {
          $("#PreviousDomain").attr("disabled", "disabled");
        } else {
          $("#PreviousDomain").attr("disabled", false);
        }
      },
      onMaxDomainReached: function(hit) {
      if (hit) {
          $("#NextDomain").attr("disabled", "disabled");
        } else {
          $("#NextDomain").attr("disabled", false);
        }
      },
    	cellSize: 10,
    	cellPadding: 1,
      domainGutter: 0,
    	range: ' . $range . ',
      itemName: ["' . t('point') . '", "' . t('points') . '"],
      domainDynamicDimension: false,
    	previousSelector: "#PreviousDomain",
    	nextSelector: "#NextDomain",
      legend: [' . $config->get('thresholds') . '],
      highlight: "now",
      weekStartOnMonday: ' . $first_day . ',
    });
    $("#CurrentDomain").on("click", function(event) {
      cal.rewind();
    });
    </script>',
  ];
}

/**
 * Implements hook_block_info().
 */
function activity_calendar_block_info() {
  $blocks['user'] = array(
    'info' => t('User activity calendar'),
    'description' => t('Block that shows user activity calendar.'),
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function activity_calendar_block_view($delta = '') {
  // Load only for registered users and when not on user pages.
  if (user_is_anonymous() || (arg(0) == 'user')) {
    return;
  }
  $block = array();
  switch ($delta) {
    case 'user':
      $block['subject'] = 'My activity';
      $block['content'] = activity_calendar_block_contents($delta);
      break;
  }
  return $block;
}


/**
 * Returns block content.
 */
function activity_calendar_block_contents($delta) {
  global $user;
  $config = config('activity_calendar.settings');
  // Load libraries.
  $path = backdrop_get_path('module', 'activity_calendar');
  backdrop_add_css($path . '/activity_calendar.css');
  backdrop_add_css($path . '/lib/cal-heatmap.css');
  backdrop_add_js($path . '/lib/d3.min.js');
  backdrop_add_js($path . '/lib/cal-heatmap.min.js');

  // Collect node points.
  if ($config->get('nodes') == 1) {
    $prefix = 'node_type_';
    foreach ($config->get() as $option => $value) {
      if (strpos($option, $prefix) !== FALSE) {
        if ($value == TRUE) {
          $content_type = str_replace($prefix, "", $option);
          $nodes = db_select('node', 'n')
          ->fields('n', array('nid', 'created'))
          ->condition('n.uid', $user->uid)
          ->condition('n.type', $content_type)
          ->condition('n.created', strtotime('first day of this month'), '>=')
          ->condition('n.status', '1')
          ->execute()->fetchAll();
          foreach ($nodes as $node) {
            $user_activity[$node->created] = intval($config->get('node_points'));
          }
        }
      }
    }
  }

  // Collect comment points.
  if ($config->get('comments') == 1) {
  $comments = db_select('comment', 'c')
      ->fields('c', array('cid', 'created'))
      ->condition('c.uid', $user->uid)
      ->condition('c.created', strtotime('first day of this month'), '>=')
      ->condition('c.status', '1')
      ->execute()->fetchAll();
      foreach ($comments as $comment) {
        $user_activity[$comment->created] = intval($config->get('comment_points'));
      }
    }
  // Sync calendar with the system's first day of the week.
  if (config_get('system.date', 'first_day') == '1') {
    $first_day = "true"; // The js requires this written as lowercase string.
  }
  else {
    $first_day = "false"; // The js requires this written as lowercase string.
  }
  $content = '<div id="user-activity-heatmap"></div>';
  $content .= '
   <script type="text/javascript">
      var user_activity = ' . json_encode($user_activity) . ';
    	var cal = new CalHeatMap();
    	cal.init({
        itemNamespace: "altagrade",
        legendColors: ["' . $config->get('color_min') . '","' . $config->get('color_max') . '"],
        itemSelector: "#user-activity-heatmap",
        domain: "month",
        data: user_activity,
        cellSize: 15,
        cellPadding: 1,
        range: 1,
        itemName: ["' . t('point') . '", "' . t('points') . '"],
        legend: [' . $config->get('thresholds') . '],
        legendVerticalPosition: "center",
	      legendOrientation: "vertical",
        label: {
      		position: "right",
      		rotate: "left"
      	},
        highlight: "now",
        weekStartOnMonday: ' . $first_day . ',
        domainDynamicDimension: false,
      });
    </script>
    ';
    return $content;
  }
