<?php

/**
 * @file
 * Flag activity module.
 */

/**
 * Implements hook_calendar().
 */
function flag_activity_calendar() {
  $config_flag_points = config_get('activity_calendar.settings', 'flag_activity');
  $flag_points = ($config_flag_points) ? $config_flag_points : 1;

  if (arg(0) == 'user') {
    // Collect all flag points as the hook is called from user page.
    $flags = db_select('flagging', 'f')
    ->fields('f', array('flagging_id', 'timestamp'))
    ->condition('f.uid', arg(1))
    ->execute()->fetchAll();
  }
  else {
    // Collect flag points only for the current month.
    global $user;
    $flags = db_select('flagging', 'f')
    ->fields('f', array('flagging_id', 'timestamp'))
    ->condition('f.uid', $user->uid)
    ->condition('f.timestamp', strtotime('first day of this month'), '>=')
    ->execute()->fetchAll();
  }

  if (!empty($flags)) {
    foreach ($flags as $flag) {
      $user_activity[$flag->timestamp] = intval($flag_points);
    }
    $result['module_name'] = 'Flag Activity';
    $result['user_activity'] = $user_activity;
  }
  return $result;
}
